import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.6.0',
  date: '2024-05-26T07:12:47.419Z',
};
export default meta;
