import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.6.0',
  date: '2025-06-16T11:02:33.504Z',
};
export default meta;
